#!/usr/bin/env python3
"""Generate a deterministic C++20 header containing editor runtime assets."""

from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_DIRECTORIES = ("editor", "fonts", "shaders", "templates")


def default_assets(asset_root: Path) -> list[str]:
    return [
        path.relative_to(asset_root).as_posix()
        for directory in DEFAULT_DIRECTORIES
        for path in (asset_root / directory).rglob("*")
        if path.is_file()
    ]


def symbol_for(relative_path: str) -> str:
    clean = "".join(character if character.isalnum() else "_" for character in relative_path)
    return f"k_{clean}"


def byte_lines(data: bytes) -> list[str]:
    if not data:
        return ["    std::byte{0x00},"]
    return [
        "    " + ", ".join(f"std::byte{{0x{value:02x}}}" for value in data[offset : offset + 12]) + ","
        for offset in range(0, len(data), 12)
    ]


def generate(asset_root: Path, output: Path, relative_paths: list[str]) -> None:
    assets: list[tuple[str, bytes]] = []
    for relative_path in sorted(dict.fromkeys(relative_paths)):
        source = asset_root / relative_path
        if not source.is_file():
            raise FileNotFoundError(f"embedded asset does not exist: {source}")
        assets.append((relative_path.replace("\\", "/"), source.read_bytes()))

    lines = [
        "// Generated by tools/embed_assets.py. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <span>",
        "#include <string_view>",
        "",
        "namespace fadix::embedded",
        "{",
        "struct Asset",
        "{",
        "    std::string_view Path;",
        "    std::span<const std::byte> Bytes;",
        "};",
        "",
    ]
    for relative_path, data in assets:
        symbol = symbol_for(relative_path)
        lines.append(f"inline constexpr std::array<std::byte, {max(1, len(data))}> {symbol}{{")
        lines.extend(byte_lines(data))
        lines.extend(["};", ""])

    lines.append(f"inline constexpr std::array<Asset, {len(assets)}> Assets{{{{")
    for relative_path, data in assets:
        symbol = symbol_for(relative_path)
        size = len(data)
        lines.append(f'    Asset{{"{relative_path}", std::span{{{symbol}.data(), {size}U}}}},')
    lines.extend(
        [
            "}};",
            "",
            "[[nodiscard]] inline constexpr const Asset* Find(const std::string_view path) noexcept",
            "{",
            "    for (const Asset& asset : Assets)",
            "    {",
            "        if (asset.Path == path)",
            "        {",
            "            return &asset;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "}",
            "",
        ]
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(lines)
    if output.exists() and output.read_text(encoding="utf-8") == content:
        return
    output.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--asset-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--asset", action="append", default=[])
    arguments = parser.parse_args()
    generate(
        arguments.asset_root.resolve(),
        arguments.output.resolve(),
        arguments.asset or default_assets(arguments.asset_root.resolve()),
    )


if __name__ == "__main__":
    main()
